### ISSUE TITLE
Data checking

### ISSUE THREAD

**Issue by trokhymchuk** [Hi-Folks/statistics#12]
There are several functions that work only with numbers (such as `Stat::harmonicMean()` or `Stat::stdev`), currently they suppose that the argument is  correct. If you pass data that cannot be converted to number (int or float), it will trigger the TypeError. And there is `Stat::mean()` which return null on non-numeric array element.

I believe that should be consistent over library and so the solutions I see
1. Return error (currently `null`) if there is inappropriate data.
2. Filter input data. 
3. Suppose data is correct, passing incorrect data is UB (undefined behavior).

Also, filtering or checking data takes some time, so the third variant should be the fastest one.

**Comment by roberto-butti** [comment]
Thank you @trokhymchuk.

I merged the #11 .
I think that is good enough to be the solution.
I see other options.
For now, we could keep #11 as solution. If something better will raise in the future we can improve the code base.
What do yuo think @trokhymchuk   ?

**Comment by trokhymchuk** [comment]
Yeah, I suppose so. So end users have `Statistics` class for safe operation without manual data-checking and Stat-functions for some low-level stuff.
