### ISSUE TITLE
Upgrade the support for rector to 0.18.5

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/statistics#34]
In the composer file, i would like to force the support to rector 0.18.5 (min mersion)

**Comment by sukuasoft** [comment]
@roberto-butti 
Can I work on this issue?

**Comment by roberto-butti** [comment]
Hello @sukuasoft , thank you for your availability.
Yes, i assigned to you. but in order to avoid conflicts, we are merging another PR into main, that i'm sure that will have impact on this issue. So if you agree:
- i will merge the other PR into main (the PR #36  )
- then, after the merging you can start to work.
is it ok for you?

Roberto

**Comment by sukuasoft** [comment]
@roberto-butti  Yes, that's fine with me

**Comment by roberto-butti** [comment]
Hi @sukuasoft  the #36  is merged 🥳

**Comment by sukuasoft** [comment]
I'm already working on this issue
@aoscode

**Comment by roberto-butti** [comment]
Thank you for the PR #38 , good job @sukuasoft
