### ISSUE TITLE
Add Pint in dev dependencies

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/statistics#35]
Add Pint
```
composer require laravel/pint --dev
```
instead of phpcsfixer.
Use the preset PER
https://www.php-fig.org/per/coding-style/

Update also the composer script, replacing php cs fixer with pint

**Comment by sukuasoft** [comment]
@roberto-butti Can I work on this issue?

**Comment by roberto-butti** [comment]
Of course @sukuasoft , I'm assigning it to you.
Thank you.

**Comment by roberto-butti** [comment]
closed by #39
