### ISSUE TITLE
Workflow updation : `.github/workflows/run-tests.yml`

### ISSUE THREAD

**Issue by Abhishek-Mallick** [Hi-Folks/statistics#59]
I tried executing it on codespaces and did a local change to update the `codespace repo`

> Code-space repo has no interaction with this [repo](https://github.com/Hi-Folks/statistics) still my local changes dosen't reflect instead creates another branch every time

I looked through the docs on `semantic-workflow` and it seems
```
on:
  push:
    branches:
      - main
```
This should solve the issue
Creating a PR for the same

**Comment by roberto-butti** [comment]
I didn't understand the issue, i tried codespace, and worked.
Please, list the detailed steps to reproduce the issue.
